import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {createConsoleFixture,TEST_TOKEN,BOT_A,BOT_B} from './console-fixture.mjs';

// Local-only UI review. No billing, provider requests or deployment.
const evidence=process.env.AVATAR_UI_EVIDENCE||'/tmp/avatar-ui-evidence';
for(const [name,viewport] of [['desktop',{width:1280,height:900}],['mobile',{width:390,height:844}]])test(`avatar review ${name}: shared theme, stale retention, single bot and image unavailable`,async()=>{
 await mkdir(evidence,{recursive:true});const fixture=await createConsoleFixture();
 const browser=await chromium.launch({executablePath:process.env.CONSOLE_CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
 const themes=[{id:'paper',name:'Paper characters',kind:'vector',prompt:'Transparent paper geometry, no circular frame',model:'gpt-6.1-sol'},{id:'angular',name:'Angular characters',kind:'vector',prompt:'Shared angular geometry',model:'gpt-6.1-sol'},{id:'image',name:'Saved image theme (unavailable)',kind:'image',prompt:'Shared portrait',model:'gpt-image-2.5-sunburst'}];
 let selection={themeId:'paper',revision:1},jobs=[],fail=true;
 const avatars=[BOT_A,BOT_B].map((botId,i)=>({botId,themeId:'paper',revision:1,status:'ready',artifactId:`prior-${i}`,mimeType:'image/svg+xml',updatedAt:'2026-10-01T00:00:00.000Z'}));
 const calls=[],headers=[],external=[],errors=[],screenshots=[];const settings=()=>({themes,selection:{...selection},avatars:structuredClone(avatars),jobs:structuredClone(jobs)});
 try{
  const page=await browser.newPage({viewport,isMobile:name==='mobile',hasTouch:name==='mobile'});page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',async route=>{const url=new URL(route.request().url());if(!['127.0.0.1','localhost'].includes(url.hostname)){external.push(url.origin);await route.abort();}else await route.continue();});
  await page.route('**/v1/avatar-settings',async route=>{if(route.request().method()==='PUT'){selection={themeId:route.request().postDataJSON().themeId,revision:selection.revision+1};avatars.forEach(a=>a.status='obsolete');}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(settings())});});
  await page.route('**/v1/avatar-models',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({connected:true,vectorModels:[{id:'gpt-6.1-sol',name:'Connected text model'}],imageModels:[],imageAvailable:false,unavailableImageModels:['sunburst','flare'].map(id=>({id:`gpt-image-2.5-${id}`,name:`GPT Image 2.5 ${id}`,available:false,reason:'Server image API is not configured.'})),imageBilling:{provider:'openai-api',separateFromChatGPT:true,costKnown:false,message:'OpenAI API billing is separate from ChatGPT/SIWC.'}})}));
  await page.route('**/v1/bots/*/avatar',async route=>{headers.push(route.request().headers());const a=route.request().url().includes(BOT_A);await route.fulfill({status:200,contentType:'image/svg+xml',body:`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><path d="${a?'M20 100L64 12L108 100Z':'M24 24H104V104H24Z'}" fill="${a?'#db9852':'#72acd8'}"/><path d="M45 55h8m22 0h8M48 78h32" stroke="#252525" stroke-width="7"/></svg>`});});
  await page.route('**/v1/avatar-generations',async route=>{const body=route.request().postDataJSON();calls.push(body);const date='2026-10-01T00:00:02.000Z';jobs=[{id:`job-${calls.length}`,operationId:body.operationId,botId:body.botId,...selection,status:fail?'failed':'completed',...(fail?{error:{code:'mock_generation_failed',message:'Mock generation failed; previous avatar retained.'}}:{}),createdAt:date,updatedAt:date}];if(!fail)Object.assign(avatars.find(a=>a.botId===body.botId),selection,{status:'ready',artifactId:'replacement-a'});await route.fulfill({status:202,contentType:'application/json',body:JSON.stringify({jobs})});});
  const shot=async suffix=>{const path=`${evidence}/${name}-${suffix}.png`;await page.screenshot({path,fullPage:true});screenshots.push(path);};
  const geometry=()=>page.locator('#settings-dialog').evaluate(n=>({viewport:innerWidth,documentWidth:document.documentElement.scrollWidth,dialogWidth:n.clientWidth,dialogScrollWidth:n.scrollWidth,dialogHeight:n.clientHeight,dialogScrollHeight:n.scrollHeight,left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right}));
  await page.goto(fixture.url);await page.locator('#token').fill(TEST_TOKEN);await page.locator('#connect-form button').click();await page.locator('#app').waitFor({state:'visible'});if(name==='mobile'){await page.locator('.bot-item .timber-avatar-image').first().waitFor({state:'visible'});await shot('bot-list');await page.locator('.bot-item').first().click();}await page.locator('#selected-avatar .timber-avatar-image').waitFor({state:name==='mobile'?'attached':'visible'});await shot('conversation');
  if(name==='mobile')await page.locator('#mobile-back').click();await page.locator('#settings-button').click();const rows=page.locator('#avatar-bot-list .avatar-bot-row');await rows.nth(1).locator('img').waitFor({state:'visible'});assert.equal(await rows.count(),2);
  const prior=await rows.nth(0).locator('img').getAttribute('src'),priorB=await rows.nth(1).locator('img').getAttribute('src');assert.notEqual(prior,priorB);
  for(const avatar of await page.locator('#avatar-bot-list .avatar-vector').all())assert.deepEqual(await avatar.evaluate(n=>{const s=getComputedStyle(n),i=getComputedStyle(n.querySelector('img'));return {radius:s.borderRadius,imageRadius:i.borderRadius,background:s.backgroundColor};}),{radius:'0px',imageRadius:'0px',background:'rgba(0, 0, 0, 0)'});
  assert.equal(await page.locator('#avatar-theme-select').count(),1);assert.equal(await rows.locator('select').count(),0,'no per-bot theme override');const initialGeometry=await geometry();await shot('settings-shared');
  await page.locator('#avatar-theme-select').selectOption('angular');await page.locator('#avatar-apply-theme').click();await page.waitForFunction(()=>document.querySelector('#avatar-status').textContent.includes('revision 2'));assert.equal(calls.length,0,'switch does not automatically generate');assert.equal(await rows.locator('.avatar-stale').count(),2);assert.equal(await rows.nth(0).locator('img').getAttribute('src'),prior);
  await rows.nth(0).getByRole('button',{name:'Regenerate',exact:true}).click();await page.getByText('Mock generation failed; previous avatar retained.',{exact:true}).waitFor({state:'visible'});assert.equal(await rows.nth(0).locator('img').getAttribute('src'),prior);assert.equal(await rows.nth(1).locator('img').getAttribute('src'),priorB);await shot('stale-failed');
  fail=false;const accepted=page.waitForResponse(r=>r.url().endsWith('/v1/avatar-generations')&&r.status()===202);await rows.nth(0).getByRole('button',{name:'Regenerate',exact:true}).click();await accepted;await page.locator('#avatar-refresh').click();await page.waitForFunction(old=>{const src=document.querySelector('#avatar-bot-list .avatar-bot-row img')?.getAttribute('src');return Boolean(src&&src!==old);},prior);assert.equal(await rows.nth(0).locator('.avatar-stale').count(),0);assert.equal(await rows.nth(1).locator('.avatar-stale').count(),1);assert.equal(await rows.nth(1).locator('img').getAttribute('src'),priorB);assert.equal(calls.length,2);for(const c of calls){assert.equal(c.botId,BOT_A);assert.equal(c.expectedThemeId,'angular');assert.equal(c.expectedRevision,2);assert.equal(c.confirmedCount,undefined);assert.equal(c.acknowledgeApiBilling,undefined);}assert.notEqual(calls[0].operationId,calls[1].operationId);await shot('single-bot-replaced');
  await page.locator('#avatar-theme-select').selectOption('image');await page.locator('#avatar-apply-theme').click();await page.waitForFunction(()=>document.querySelector('#avatar-status').textContent.includes('revision 3'));assert.equal(await page.locator('#avatar-generate-all').isDisabled(),true);for(const b of await rows.getByRole('button',{name:'Regenerate',exact:true}).all())assert.equal(await b.isDisabled(),true);
  await page.locator('#avatar-create-details > summary').click();await page.locator('#avatar-theme-kind').selectOption('image');await page.locator('#avatar-image-capability').scrollIntoViewIfNeeded();const capability=await page.locator('#avatar-image-capability').textContent();for(const re of [/unavailable/i,/not configured/i,/no image will be generated/i,/Cost is unknown/i])assert.match(capability,re);assert.equal(calls.length,2);const expandedGeometry=await geometry();await shot('image-unavailable');
  // Collect measurements before assertions so a layout regression retains useful evidence.
  await writeFile(`${evidence}/${name}-checks.json`,JSON.stringify({viewport,initialGeometry,expandedGeometry,calls,imageRequestCount:headers.length,external,errors,screenshots},null,2));
  for(const g of [initialGeometry,expandedGeometry]){assert.ok(g.documentWidth<=viewport.width+1,`page horizontal overflow: ${JSON.stringify(g)}`);assert.ok(g.dialogScrollWidth<=g.dialogWidth+1,`modal horizontal overflow: ${JSON.stringify(g)}`);assert.ok(g.left>=0&&g.right<=viewport.width+1,'modal inside viewport');}
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.ok(headers.length>=2);for(const h of headers){assert.equal(h.authorization,undefined);assert.equal(h['x-timber-client'],'console');assert.match(h.cookie||'',/timber_fixture_session=/);}await page.close();
 }finally{await browser.close();await fixture.close();}
});
